name: bill_reminder
version: 1.0.0+1
description: A professional bill reminder app.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  fl_chart: ^0.68.0
  csv: ^6.0.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
